### ISSUE TITLE
iWalk App ----> Check the Menu interface ( see the screenshot)

### ISSUE THREAD

**Issue by ginaCFSJ** [sfbrigade/intentional-walk-client#43] opened 2024-01-16 00:22 UTC
![Screenshot 2024-01-15 at 4 22 54 PM](https://github.com/sfbrigade/intentional-walk/assets/84778368/04e8ba5b-ae04-4e24-b73e-5e4c1eaa1c16)

Environment - iOS 17.2.1 9 iPhone 11

**Comment by francisli** [comment] 2024-05-09 17:05
I'm going to close this issue, as the behaviour of the menu sliding in from the left and pushing the main screen to the right (and leaving it partially visible) is by design.

**Closed by francisli** 2024-05-09 17:05 UTC
